Write-host "Hyzero Programming Language"
Write-host "Version: v0.1.0"
Write-host "Original Author: Cyril John Magayaga"
Write-host "Developer(s): Cyril John Magayaga"
Write-host "Release Date: August 15, 2022"