Write-host "Hyzero Programming Language"
Write-host "Version History"
Write-host "Original Author: Cyril John Magayaga"
Write-host "Developer(s): Cyril John Magayaga"
Write-host "Versions      | Release Dates         | Developer(s)       "
Write-host "v0.0.1        | July 30, 2022         | Cyril John Magayaga"
Write-host "v0.0.2        | August 6, 2022        | Cyril John Magayaga"
Write-host "v0.0.3        | August 10, 2022       | Cyril John Magayaga"