Write-host "Hyzero Programming Language"
Write-host "Version: v0.0.2"
Write-host "Original Author: Cyril John Magayaga"
Write-host "Developer(s): Cyril John Magayaga"
Write-host "Release Date: August 6, 2022"